language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 5.4
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 7.0
    env: WP_VERSION=4.5 WP_MULTISITE=0
  - php: 7.0
    env: WP_VERSION=4.4 WP_MULTISITE=0
  - php: 5.4
    env: WP_VERSION=4.3 WP_MULTISITE=0
  - php: 5.4
    env: WP_VERSION=4.2 WP_MULTISITE=0

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
  - if find . -name "*.php" -exec php -l {} \; | grep "unexpected $end"; then exit 1; fi
  - composer install --prefer-source --optimize-autoloader --no-scripts
  - bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION
  - if [[ $WP_MULTISITE = 1 ]]; then nvm install 4.5 && npm install -g karma-cli && npm install; fi

script:
 - if [[ $WP_MULTISITE = 1 ]]; then npm run test; fi
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist --group ajax

