language: php

sudo: false

services:
  - mysql

addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
      key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - yarn

cache:
  yarn: true
  directories:
  - $HOME/.composer/cache/files

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

env:
- WP_VERSION=latest WP_MULTISITE=0 PLUGIN=gravity-forms-pdf-extended

matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=1 COVERAGE=1
  - php: 7.2
    env: LINT=1

before_install:
- |
  if [[ "$LINT" == "1" ]]; then
    export PHPCS_DIR=/tmp/phpcs
    export LINTS_DIR=/tmp/lint
    git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
    git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $LINTS_DIR
    $PHPCS_DIR/bin/phpcs --config-set installed_paths $LINTS_DIR
    phpenv rehash
  fi;

before_script:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini; fi
- if find . -name "*.php" -exec php -l {} \; | grep "unexpected $end"; then exit 1; fi
- composer install --prefer-source --optimize-autoloader --no-scripts
- bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION
- if [[ "$WP_MULTISITE" = "1" ]]; then nvm install 10.15 && yarn global add karma-cli && yarn; fi
- if [ -n "$TRAVIS_TAG" ]; then nvm install 10.15; fi

script:
- |
  if [[ "$LINT" == "1" ]]; then
    $PHPCS_DIR/bin/phpcs -p .
  elif [[ "$COVERAGE" == "1" ]]; then
   yarn run test:coverage
   ./vendor/bin/phpunit --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml -c tests/phpunit/phpunit.xml.
   ./vendor/bin/phpunit --coverage-clover=tmp/coverage/report-xml/php-coverage2.xml -c tests/phpunit/phpunit.xml.dist --group ajax
   yarn run lint
  else
   ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist
   ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist --group ajax
  fi

after_success:
-  if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash); fi

before_deploy:
-  if [[ $TRAVIS_TAG ]]; then bash ./bin/build.sh $TRAVIS_TAG $TRAVIS_BRANCH; fi

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./bin/deploy.sh
  on:
    tags: true
    php: 5.6
