language: php

sudo: false

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0 PLUGIN=gravity-forms-pdf-extended

matrix:
  include:
  - php: 7.1
    env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
  - if find . -name "*.php" -exec php -l {} \; | grep "unexpected $end"; then exit 1; fi
  - composer install --prefer-source --optimize-autoloader --no-scripts
  - bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION
  - if [[ $WP_MULTISITE = 1 ]]; then nvm install 6.10 && yarn global add karma-cli && yarn; fi

script:
 - if [[ $WP_MULTISITE = 1 ]]; then yarn run test; fi
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist
 - vendor/bin/phpunit -c tests/phpunit/phpunit.xml.dist --group ajax

before_deploy:
  if [[ $TRAVIS_TAG ]]; then bash ./bin/build.sh $TRAVIS_TAG $TRAVIS_BRANCH; fi

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./bin/deploy.sh
  on:
    tags: true
    php: 5.4